#! /bin/bash

set -e
pkg=lex_bot_tester
dry_run=false
if [[ $# > 0 ]]
then
    if [[ "$1" == '-n' || "$1" == '--dry-run' ]]
    then
        dry_run=true
    fi
fi
eval $(grep version setup.py | sed 's/,$//')
tag="v$version"
if ! $dry_run
then
    git tag "$tag"
    git push --tags
fi
if [[ README.md -nt README.rst ]]
then
    pandoc=$(which pandoc)
    if [[ -n "$pandoc" ]]
    then
        $pandoc --from=markdown --to=rst --output=README.rst README.md
    fi
fi
/usr/bin/python setup.py bdist_egg bdist_wheel --universal
if ! $dry_run
then
    twine upload dist/${pkg}-${version}-*
fi
